-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Category" ADD VALUE 'AUTO_MOTO';
ALTER TYPE "Category" ADD VALUE 'AUTO_PARTS';
ALTER TYPE "Category" ADD VALUE 'MOTO_PARTS';
ALTER TYPE "Category" ADD VALUE 'AUTO_ACCESSORIES';
ALTER TYPE "Category" ADD VALUE 'AUTO_EQUIPMENT';
ALTER TYPE "Category" ADD VALUE 'APPLIANCES';
ALTER TYPE "Category" ADD VALUE 'FRIDGE_PARTS';
ALTER TYPE "Category" ADD VALUE 'WASHING_MACHINE_PARTS';
ALTER TYPE "Category" ADD VALUE 'AC_PARTS';
ALTER TYPE "Category" ADD VALUE 'MICROWAVE_PARTS';
ALTER TYPE "Category" ADD VALUE 'HOME_DIY';
ALTER TYPE "Category" ADD VALUE 'TOOLS';
ALTER TYPE "Category" ADD VALUE 'ELECTRICAL_MATERIAL';
ALTER TYPE "Category" ADD VALUE 'PLUMBING';
ALTER TYPE "Category" ADD VALUE 'CARPENTRY';
ALTER TYPE "Category" ADD VALUE 'ENERGY_INDUSTRY';
ALTER TYPE "Category" ADD VALUE 'GENERATORS';
ALTER TYPE "Category" ADD VALUE 'SOLAR_PANELS';
ALTER TYPE "Category" ADD VALUE 'INDUSTRIAL_BATTERIES';
ALTER TYPE "Category" ADD VALUE 'INDUSTRIAL_MACHINE_PARTS';
ALTER TYPE "Category" ADD VALUE 'MULTIMEDIA_GAMING';
ALTER TYPE "Category" ADD VALUE 'CONSOLES';
ALTER TYPE "Category" ADD VALUE 'CONTROLLERS';
ALTER TYPE "Category" ADD VALUE 'CONSOLE_PARTS';
ALTER TYPE "Category" ADD VALUE 'GAMING_ACCESSORIES';
ALTER TYPE "Category" ADD VALUE 'OTHER_VEHICLES';
ALTER TYPE "Category" ADD VALUE 'BICYCLE';
ALTER TYPE "Category" ADD VALUE 'SCOOTER';
ALTER TYPE "Category" ADD VALUE 'VARIOUS_PARTS';

-- AlterEnum
ALTER TYPE "Condition" ADD VALUE 'SECONDE_MAIN';
